// <auto-generated />
namespace team22project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class whatever : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whatever));
        
        string IMigrationMetadata.Id
        {
            get { return "201805040203404_whatever"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
